model:
  encoder: 'resnet18'
  optimizer:
    name: Adam
    lr: 0.0001
    weight_decay: 3e-4

test_path: "D:/Train-Custom-Classification/BW_CNN Model_16Ch/data"
model_path: "D:/Train-Custom-Classification/outputs/2024-12-20/17-47-50/model.pth"
image: "D:/Train-Custom-Classification/BW_CNN Model_16Ch/data/Arriba/sub-01_ses-01_Arriba_Epoch1_D3-epo.jpeg"
num_classes: 4
batch_size: 4
target_size: [224, 224]
max_epochs: 20