model:
  encoder: 'mobilenetv2_100'
  num_classes: 3
  batch_size: 8
  target_size: [224, 224]
  max_epochs: 20
  optimizer:
    name: Adam
    lr: 0.0001
    weight_decay: 3e-4

dataset: 
  train_path: "/home/saeed101/projects/Train-Custom-Classification/dataset/train"
  val_path: "/home/saeed101/projects/Train-Custom-Classification/dataset/valid"
  test_path: "/home/saeed101/projects/Train-Custom-Classification/dataset/test"